{
    "name": "Hotel Management",
    "version": "17.0.1.0.0",
    "category": "Addons",
    "summary": "Hotel Management adalah addons untuk odoo 17",
    "description": """Untuk Mengelola Hotel mu""",
    "author": "RAFIF FZ",
    "company": "PT RAFIF FZ",
    "maintainer": "RAFIF FZ",
    "depends": ["web", "mail", "product"],
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/room_booking_view.xml",
        "views/hotel_floor_view.xml",
        "views/hotel_amenity_view.xml",
        "views/hotel_services_view.xml",
        "views/hotel_room_view.xml",     
        "views/hotel_menu.xml",
        "wizard/room_booking_detail_view.xml",
        "views/room_booking_reports_menu.xml",  
        "report/room_booking_reports.xml",     
    ],
    "assets": {
    },
    "installable": True,
    "auto_install": False,
    "application": False,
}